language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5
  - LARAVEL=5.6
  - LARAVEL=5.7
  - LARAVEL=5.8
  - LARAVEL=6.0
  - LARAVEL=6.18
  - LARAVEL=7.0
  - LARAVEL=7.28
  - LARAVEL=8.0
  - LARAVEL=8.1

matrix:
  exclude:
    - php: '7.2'
      env: 'LARAVEL=8.0'
    - php: '7.2'
      env: 'LARAVEL=8.1'

script:
  - vendor/bin/phpunit --testdox

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]+$ ]] && MAJOR=6 || MAJOR=5'
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || true'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: FHjnvS2Jjp/erTN0rNHD//lPvih9WMQik27IN6pIAG664poq3/NMOisVWVGKizlUDNQSszBotQN/gJA+10ZoeErpgkTRvtDVFUfqrdvIeeWA3zbv6tP7pH3lvOuhdREII04sM2EFQxJriF3oNrHakNJB7nJDRq5Ft8gzPUVVUhug4cFSyPyKIgHkr3FGx6WiRYP3ScqtiS5MRMwnGJ9kVnQWasdoCJaqD4EjdKQDxxglFmLKe4cwRPUQedRuFPEShYwXTnnvRISrZimbkfYlOf4prohheslLxUEoFGVx+zjFudqyCh6WF5/uBF8JurcnpVNKQ0Krbfzp8n+EUY0gvIBgbwxMk9396YXi1X2AnukhnKWVq71drTfitZIqI7om5yIMMrLs43i8JDppc/yd2o6Hy7qGYDuP1y8USRCVLndpUJIlYixYspza38jxJdt0sflDIP0XCQKxg4z7h2Dgk7OKgw4499FMz+NdAhqk2RcHcbuaffSynyNHziNSP3osLTAfLnZA9jzDK++eg4hy2LUh21TW5uJ30TF9jiO0ViGM1y2V8wowXKc3C2ioWNCs8xVnylYYL3TzpSre47mgzn0lMmjY67VPeFg+Fl6plBHuvlpWI5+ld2wsIrW11zFWP/kf86cDNFmv7yDlauE8CPVUOK+ty0EsxpZ37897rUA=
